// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Data_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Data_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Data_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Data_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Data_2eproto;
class AnyDataType;
struct AnyDataTypeDefaultTypeInternal;
extern AnyDataTypeDefaultTypeInternal _AnyDataType_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::AnyDataType* Arena::CreateMaybeMessage<::AnyDataType>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class AnyDataType final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AnyDataType) */ {
 public:
  inline AnyDataType() : AnyDataType(nullptr) {}
  ~AnyDataType() override;
  explicit constexpr AnyDataType(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AnyDataType(const AnyDataType& from);
  AnyDataType(AnyDataType&& from) noexcept
    : AnyDataType() {
    *this = ::std::move(from);
  }

  inline AnyDataType& operator=(const AnyDataType& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnyDataType& operator=(AnyDataType&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AnyDataType& default_instance() {
    return *internal_default_instance();
  }
  enum DataCase {
    kIntValue = 1,
    kInt64Value = 2,
    kUint32Value = 3,
    kUint64Value = 4,
    kFloatValue = 5,
    kDoubleValue = 6,
    kBoolValue = 7,
    kStringValue = 8,
    kBytesValue = 9,
    DATA_NOT_SET = 0,
  };

  static inline const AnyDataType* internal_default_instance() {
    return reinterpret_cast<const AnyDataType*>(
               &_AnyDataType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AnyDataType& a, AnyDataType& b) {
    a.Swap(&b);
  }
  inline void Swap(AnyDataType* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnyDataType* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnyDataType* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AnyDataType>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AnyDataType& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AnyDataType& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AnyDataType* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AnyDataType";
  }
  protected:
  explicit AnyDataType(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIntValueFieldNumber = 1,
    kInt64ValueFieldNumber = 2,
    kUint32ValueFieldNumber = 3,
    kUint64ValueFieldNumber = 4,
    kFloatValueFieldNumber = 5,
    kDoubleValueFieldNumber = 6,
    kBoolValueFieldNumber = 7,
    kStringValueFieldNumber = 8,
    kBytesValueFieldNumber = 9,
  };
  // int32 int_value = 1;
  bool has_int_value() const;
  private:
  bool _internal_has_int_value() const;
  public:
  void clear_int_value();
  int32_t int_value() const;
  void set_int_value(int32_t value);
  private:
  int32_t _internal_int_value() const;
  void _internal_set_int_value(int32_t value);
  public:

  // int64 int64_value = 2;
  bool has_int64_value() const;
  private:
  bool _internal_has_int64_value() const;
  public:
  void clear_int64_value();
  int64_t int64_value() const;
  void set_int64_value(int64_t value);
  private:
  int64_t _internal_int64_value() const;
  void _internal_set_int64_value(int64_t value);
  public:

  // uint32 uint32_value = 3;
  bool has_uint32_value() const;
  private:
  bool _internal_has_uint32_value() const;
  public:
  void clear_uint32_value();
  uint32_t uint32_value() const;
  void set_uint32_value(uint32_t value);
  private:
  uint32_t _internal_uint32_value() const;
  void _internal_set_uint32_value(uint32_t value);
  public:

  // uint64 uint64_value = 4;
  bool has_uint64_value() const;
  private:
  bool _internal_has_uint64_value() const;
  public:
  void clear_uint64_value();
  uint64_t uint64_value() const;
  void set_uint64_value(uint64_t value);
  private:
  uint64_t _internal_uint64_value() const;
  void _internal_set_uint64_value(uint64_t value);
  public:

  // float float_value = 5;
  bool has_float_value() const;
  private:
  bool _internal_has_float_value() const;
  public:
  void clear_float_value();
  float float_value() const;
  void set_float_value(float value);
  private:
  float _internal_float_value() const;
  void _internal_set_float_value(float value);
  public:

  // double double_value = 6;
  bool has_double_value() const;
  private:
  bool _internal_has_double_value() const;
  public:
  void clear_double_value();
  double double_value() const;
  void set_double_value(double value);
  private:
  double _internal_double_value() const;
  void _internal_set_double_value(double value);
  public:

  // bool bool_value = 7;
  bool has_bool_value() const;
  private:
  bool _internal_has_bool_value() const;
  public:
  void clear_bool_value();
  bool bool_value() const;
  void set_bool_value(bool value);
  private:
  bool _internal_bool_value() const;
  void _internal_set_bool_value(bool value);
  public:

  // string string_value = 8;
  bool has_string_value() const;
  private:
  bool _internal_has_string_value() const;
  public:
  void clear_string_value();
  const std::string& string_value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_string_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_string_value();
  PROTOBUF_NODISCARD std::string* release_string_value();
  void set_allocated_string_value(std::string* string_value);
  private:
  const std::string& _internal_string_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_string_value(const std::string& value);
  std::string* _internal_mutable_string_value();
  public:

  // bytes bytes_value = 9;
  bool has_bytes_value() const;
  private:
  bool _internal_has_bytes_value() const;
  public:
  void clear_bytes_value();
  const std::string& bytes_value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bytes_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bytes_value();
  PROTOBUF_NODISCARD std::string* release_bytes_value();
  void set_allocated_bytes_value(std::string* bytes_value);
  private:
  const std::string& _internal_bytes_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bytes_value(const std::string& value);
  std::string* _internal_mutable_bytes_value();
  public:

  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:AnyDataType)
 private:
  class _Internal;
  void set_has_int_value();
  void set_has_int64_value();
  void set_has_uint32_value();
  void set_has_uint64_value();
  void set_has_float_value();
  void set_has_double_value();
  void set_has_bool_value();
  void set_has_string_value();
  void set_has_bytes_value();

  inline bool has_data() const;
  inline void clear_has_data();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union DataUnion {
    constexpr DataUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    int32_t int_value_;
    int64_t int64_value_;
    uint32_t uint32_value_;
    uint64_t uint64_value_;
    float float_value_;
    double double_value_;
    bool bool_value_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr string_value_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bytes_value_;
  } data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint32_t _oneof_case_[1];

  friend struct ::TableStruct_Data_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AnyDataType

// int32 int_value = 1;
inline bool AnyDataType::_internal_has_int_value() const {
  return data_case() == kIntValue;
}
inline bool AnyDataType::has_int_value() const {
  return _internal_has_int_value();
}
inline void AnyDataType::set_has_int_value() {
  _oneof_case_[0] = kIntValue;
}
inline void AnyDataType::clear_int_value() {
  if (_internal_has_int_value()) {
    data_.int_value_ = 0;
    clear_has_data();
  }
}
inline int32_t AnyDataType::_internal_int_value() const {
  if (_internal_has_int_value()) {
    return data_.int_value_;
  }
  return 0;
}
inline void AnyDataType::_internal_set_int_value(int32_t value) {
  if (!_internal_has_int_value()) {
    clear_data();
    set_has_int_value();
  }
  data_.int_value_ = value;
}
inline int32_t AnyDataType::int_value() const {
  // @@protoc_insertion_point(field_get:AnyDataType.int_value)
  return _internal_int_value();
}
inline void AnyDataType::set_int_value(int32_t value) {
  _internal_set_int_value(value);
  // @@protoc_insertion_point(field_set:AnyDataType.int_value)
}

// int64 int64_value = 2;
inline bool AnyDataType::_internal_has_int64_value() const {
  return data_case() == kInt64Value;
}
inline bool AnyDataType::has_int64_value() const {
  return _internal_has_int64_value();
}
inline void AnyDataType::set_has_int64_value() {
  _oneof_case_[0] = kInt64Value;
}
inline void AnyDataType::clear_int64_value() {
  if (_internal_has_int64_value()) {
    data_.int64_value_ = int64_t{0};
    clear_has_data();
  }
}
inline int64_t AnyDataType::_internal_int64_value() const {
  if (_internal_has_int64_value()) {
    return data_.int64_value_;
  }
  return int64_t{0};
}
inline void AnyDataType::_internal_set_int64_value(int64_t value) {
  if (!_internal_has_int64_value()) {
    clear_data();
    set_has_int64_value();
  }
  data_.int64_value_ = value;
}
inline int64_t AnyDataType::int64_value() const {
  // @@protoc_insertion_point(field_get:AnyDataType.int64_value)
  return _internal_int64_value();
}
inline void AnyDataType::set_int64_value(int64_t value) {
  _internal_set_int64_value(value);
  // @@protoc_insertion_point(field_set:AnyDataType.int64_value)
}

// uint32 uint32_value = 3;
inline bool AnyDataType::_internal_has_uint32_value() const {
  return data_case() == kUint32Value;
}
inline bool AnyDataType::has_uint32_value() const {
  return _internal_has_uint32_value();
}
inline void AnyDataType::set_has_uint32_value() {
  _oneof_case_[0] = kUint32Value;
}
inline void AnyDataType::clear_uint32_value() {
  if (_internal_has_uint32_value()) {
    data_.uint32_value_ = 0u;
    clear_has_data();
  }
}
inline uint32_t AnyDataType::_internal_uint32_value() const {
  if (_internal_has_uint32_value()) {
    return data_.uint32_value_;
  }
  return 0u;
}
inline void AnyDataType::_internal_set_uint32_value(uint32_t value) {
  if (!_internal_has_uint32_value()) {
    clear_data();
    set_has_uint32_value();
  }
  data_.uint32_value_ = value;
}
inline uint32_t AnyDataType::uint32_value() const {
  // @@protoc_insertion_point(field_get:AnyDataType.uint32_value)
  return _internal_uint32_value();
}
inline void AnyDataType::set_uint32_value(uint32_t value) {
  _internal_set_uint32_value(value);
  // @@protoc_insertion_point(field_set:AnyDataType.uint32_value)
}

// uint64 uint64_value = 4;
inline bool AnyDataType::_internal_has_uint64_value() const {
  return data_case() == kUint64Value;
}
inline bool AnyDataType::has_uint64_value() const {
  return _internal_has_uint64_value();
}
inline void AnyDataType::set_has_uint64_value() {
  _oneof_case_[0] = kUint64Value;
}
inline void AnyDataType::clear_uint64_value() {
  if (_internal_has_uint64_value()) {
    data_.uint64_value_ = uint64_t{0u};
    clear_has_data();
  }
}
inline uint64_t AnyDataType::_internal_uint64_value() const {
  if (_internal_has_uint64_value()) {
    return data_.uint64_value_;
  }
  return uint64_t{0u};
}
inline void AnyDataType::_internal_set_uint64_value(uint64_t value) {
  if (!_internal_has_uint64_value()) {
    clear_data();
    set_has_uint64_value();
  }
  data_.uint64_value_ = value;
}
inline uint64_t AnyDataType::uint64_value() const {
  // @@protoc_insertion_point(field_get:AnyDataType.uint64_value)
  return _internal_uint64_value();
}
inline void AnyDataType::set_uint64_value(uint64_t value) {
  _internal_set_uint64_value(value);
  // @@protoc_insertion_point(field_set:AnyDataType.uint64_value)
}

// float float_value = 5;
inline bool AnyDataType::_internal_has_float_value() const {
  return data_case() == kFloatValue;
}
inline bool AnyDataType::has_float_value() const {
  return _internal_has_float_value();
}
inline void AnyDataType::set_has_float_value() {
  _oneof_case_[0] = kFloatValue;
}
inline void AnyDataType::clear_float_value() {
  if (_internal_has_float_value()) {
    data_.float_value_ = 0;
    clear_has_data();
  }
}
inline float AnyDataType::_internal_float_value() const {
  if (_internal_has_float_value()) {
    return data_.float_value_;
  }
  return 0;
}
inline void AnyDataType::_internal_set_float_value(float value) {
  if (!_internal_has_float_value()) {
    clear_data();
    set_has_float_value();
  }
  data_.float_value_ = value;
}
inline float AnyDataType::float_value() const {
  // @@protoc_insertion_point(field_get:AnyDataType.float_value)
  return _internal_float_value();
}
inline void AnyDataType::set_float_value(float value) {
  _internal_set_float_value(value);
  // @@protoc_insertion_point(field_set:AnyDataType.float_value)
}

// double double_value = 6;
inline bool AnyDataType::_internal_has_double_value() const {
  return data_case() == kDoubleValue;
}
inline bool AnyDataType::has_double_value() const {
  return _internal_has_double_value();
}
inline void AnyDataType::set_has_double_value() {
  _oneof_case_[0] = kDoubleValue;
}
inline void AnyDataType::clear_double_value() {
  if (_internal_has_double_value()) {
    data_.double_value_ = 0;
    clear_has_data();
  }
}
inline double AnyDataType::_internal_double_value() const {
  if (_internal_has_double_value()) {
    return data_.double_value_;
  }
  return 0;
}
inline void AnyDataType::_internal_set_double_value(double value) {
  if (!_internal_has_double_value()) {
    clear_data();
    set_has_double_value();
  }
  data_.double_value_ = value;
}
inline double AnyDataType::double_value() const {
  // @@protoc_insertion_point(field_get:AnyDataType.double_value)
  return _internal_double_value();
}
inline void AnyDataType::set_double_value(double value) {
  _internal_set_double_value(value);
  // @@protoc_insertion_point(field_set:AnyDataType.double_value)
}

// bool bool_value = 7;
inline bool AnyDataType::_internal_has_bool_value() const {
  return data_case() == kBoolValue;
}
inline bool AnyDataType::has_bool_value() const {
  return _internal_has_bool_value();
}
inline void AnyDataType::set_has_bool_value() {
  _oneof_case_[0] = kBoolValue;
}
inline void AnyDataType::clear_bool_value() {
  if (_internal_has_bool_value()) {
    data_.bool_value_ = false;
    clear_has_data();
  }
}
inline bool AnyDataType::_internal_bool_value() const {
  if (_internal_has_bool_value()) {
    return data_.bool_value_;
  }
  return false;
}
inline void AnyDataType::_internal_set_bool_value(bool value) {
  if (!_internal_has_bool_value()) {
    clear_data();
    set_has_bool_value();
  }
  data_.bool_value_ = value;
}
inline bool AnyDataType::bool_value() const {
  // @@protoc_insertion_point(field_get:AnyDataType.bool_value)
  return _internal_bool_value();
}
inline void AnyDataType::set_bool_value(bool value) {
  _internal_set_bool_value(value);
  // @@protoc_insertion_point(field_set:AnyDataType.bool_value)
}

// string string_value = 8;
inline bool AnyDataType::_internal_has_string_value() const {
  return data_case() == kStringValue;
}
inline bool AnyDataType::has_string_value() const {
  return _internal_has_string_value();
}
inline void AnyDataType::set_has_string_value() {
  _oneof_case_[0] = kStringValue;
}
inline void AnyDataType::clear_string_value() {
  if (_internal_has_string_value()) {
    data_.string_value_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
    clear_has_data();
  }
}
inline const std::string& AnyDataType::string_value() const {
  // @@protoc_insertion_point(field_get:AnyDataType.string_value)
  return _internal_string_value();
}
template <typename ArgT0, typename... ArgT>
inline void AnyDataType::set_string_value(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_string_value()) {
    clear_data();
    set_has_string_value();
    data_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  data_.string_value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:AnyDataType.string_value)
}
inline std::string* AnyDataType::mutable_string_value() {
  std::string* _s = _internal_mutable_string_value();
  // @@protoc_insertion_point(field_mutable:AnyDataType.string_value)
  return _s;
}
inline const std::string& AnyDataType::_internal_string_value() const {
  if (_internal_has_string_value()) {
    return data_.string_value_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void AnyDataType::_internal_set_string_value(const std::string& value) {
  if (!_internal_has_string_value()) {
    clear_data();
    set_has_string_value();
    data_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  data_.string_value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AnyDataType::_internal_mutable_string_value() {
  if (!_internal_has_string_value()) {
    clear_data();
    set_has_string_value();
    data_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return data_.string_value_.Mutable(
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AnyDataType::release_string_value() {
  // @@protoc_insertion_point(field_release:AnyDataType.string_value)
  if (_internal_has_string_value()) {
    clear_has_data();
    return data_.string_value_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
  } else {
    return nullptr;
  }
}
inline void AnyDataType::set_allocated_string_value(std::string* string_value) {
  if (has_data()) {
    clear_data();
  }
  if (string_value != nullptr) {
    set_has_string_value();
    data_.string_value_.UnsafeSetDefault(string_value);
    ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArenaForAllocation();
    if (arena != nullptr) {
      arena->Own(string_value);
    }
  }
  // @@protoc_insertion_point(field_set_allocated:AnyDataType.string_value)
}

// bytes bytes_value = 9;
inline bool AnyDataType::_internal_has_bytes_value() const {
  return data_case() == kBytesValue;
}
inline bool AnyDataType::has_bytes_value() const {
  return _internal_has_bytes_value();
}
inline void AnyDataType::set_has_bytes_value() {
  _oneof_case_[0] = kBytesValue;
}
inline void AnyDataType::clear_bytes_value() {
  if (_internal_has_bytes_value()) {
    data_.bytes_value_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
    clear_has_data();
  }
}
inline const std::string& AnyDataType::bytes_value() const {
  // @@protoc_insertion_point(field_get:AnyDataType.bytes_value)
  return _internal_bytes_value();
}
template <typename ArgT0, typename... ArgT>
inline void AnyDataType::set_bytes_value(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_bytes_value()) {
    clear_data();
    set_has_bytes_value();
    data_.bytes_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  data_.bytes_value_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:AnyDataType.bytes_value)
}
inline std::string* AnyDataType::mutable_bytes_value() {
  std::string* _s = _internal_mutable_bytes_value();
  // @@protoc_insertion_point(field_mutable:AnyDataType.bytes_value)
  return _s;
}
inline const std::string& AnyDataType::_internal_bytes_value() const {
  if (_internal_has_bytes_value()) {
    return data_.bytes_value_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void AnyDataType::_internal_set_bytes_value(const std::string& value) {
  if (!_internal_has_bytes_value()) {
    clear_data();
    set_has_bytes_value();
    data_.bytes_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  data_.bytes_value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AnyDataType::_internal_mutable_bytes_value() {
  if (!_internal_has_bytes_value()) {
    clear_data();
    set_has_bytes_value();
    data_.bytes_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return data_.bytes_value_.Mutable(
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AnyDataType::release_bytes_value() {
  // @@protoc_insertion_point(field_release:AnyDataType.bytes_value)
  if (_internal_has_bytes_value()) {
    clear_has_data();
    return data_.bytes_value_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
  } else {
    return nullptr;
  }
}
inline void AnyDataType::set_allocated_bytes_value(std::string* bytes_value) {
  if (has_data()) {
    clear_data();
  }
  if (bytes_value != nullptr) {
    set_has_bytes_value();
    data_.bytes_value_.UnsafeSetDefault(bytes_value);
    ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArenaForAllocation();
    if (arena != nullptr) {
      arena->Own(bytes_value);
    }
  }
  // @@protoc_insertion_point(field_set_allocated:AnyDataType.bytes_value)
}

inline bool AnyDataType::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void AnyDataType::clear_has_data() {
  _oneof_case_[0] = DATA_NOT_SET;
}
inline AnyDataType::DataCase AnyDataType::data_case() const {
  return AnyDataType::DataCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Data_2eproto
